/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// NodeTopologyInfoApplyConfiguration represents a declarative configuration of the NodeTopologyInfo type for use
// with apply.
type NodeTopologyInfoApplyConfiguration struct {
	NodeID     *int32            `json:"nodeId,omitempty"`
	Resources  map[string]int64  `json:"resources,omitempty"`
	Properties map[string]string `json:"properties,omitempty"`
}

// NodeTopologyInfoApplyConfiguration constructs a declarative configuration of the NodeTopologyInfo type for use with
// apply.
func NodeTopologyInfo() *NodeTopologyInfoApplyConfiguration {
	return &NodeTopologyInfoApplyConfiguration{}
}

// WithNodeID sets the NodeID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeID field is set to the value of the last call.
func (b *NodeTopologyInfoApplyConfiguration) WithNodeID(value int32) *NodeTopologyInfoApplyConfiguration {
	b.NodeID = &value
	return b
}

// WithResources puts the entries into the Resources field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Resources field,
// overwriting an existing map entries in Resources field with the same key.
func (b *NodeTopologyInfoApplyConfiguration) WithResources(entries map[string]int64) *NodeTopologyInfoApplyConfiguration {
	if b.Resources == nil && len(entries) > 0 {
		b.Resources = make(map[string]int64, len(entries))
	}
	for k, v := range entries {
		b.Resources[k] = v
	}
	return b
}

// WithProperties puts the entries into the Properties field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Properties field,
// overwriting an existing map entries in Properties field with the same key.
func (b *NodeTopologyInfoApplyConfiguration) WithProperties(entries map[string]string) *NodeTopologyInfoApplyConfiguration {
	if b.Properties == nil && len(entries) > 0 {
		b.Properties = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Properties[k] = v
	}
	return b
}
